### PR TITLE
Quickfix: train file name

### PR DESCRIPTION
**Pull request by zanellia**
Train file name does not match name used in the scripts in `simulations` (_intercity_ vs _Intercity_).

### CODE REVIEW

**Comment by juxhino92** [comment]
@dkouzoup: could you also please rename the file accordingly in the TTOBench repository, within the branch that you are working on for EB?

**Comment by JuxhinoKavaja** [comment]
@zanellia, just had a chat with Dimitris. He advises to keep the name with capital I. Unless, you want to do it I can take care of changing it. I will also address the issue with the unit test that you mentioned...

**Comment by zanellia** [comment]
@juxhino92 sure, will do this, thanks.

**Comment by JuxhinoKavaja** [comment]
Nice, thank you!

**Comment by dkouzoup** [comment]
Thanks for taking care of it guys. @juxhino92 can you please also update the id name inside the json file? I think it's still with lower case i

**Comment by JuxhinoKavaja** [comment]
Oh, I did not notice it. Sure, I can do it as anyhow I have to see what is wrong with the unittest.

**Pull request merged**
